service: amazon-translate
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - translate:TranslateText
        - comprehend:DetectDominantLanguage
      Resource:
        - "*"
  environment: ${self:custom.environment.${self:provider.stage}}
plugins:
  - serverless-python-requirements
functions:
  message:
    handler: handler.message
    events:
      - eventBridge:
          eventBus: arn:aws:events:ap-northeast-1:xxxxxxxxxxxx:event-bus/aws.partner/zendesk.com/xxxxxxxx/default
          pattern:
            resources:
              - 'Support Ticket'
            detail-type:
              - 'Support Ticket: Ticket Created'
custom:
  pythonRequirements:
    usePipenv: true
  environment:
    dev:
      ZENDESK_SECRET: trial/zendesk
      # https://docs.aws.amazon.com/translate/latest/dg/what-is.html
      # See also "Supported Languages and Language Codes"
      TARGET_LANG: ja
package:
  exclude:
    - .git/**